In [ ]:
# SHAYAN HASSAN ABBASI
# 01-134212-167
# BS(CS)-7B

In [2]:
# TASK no. 01. (Matrix Addition)

import numpy as np
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

print("Enter the entries for the first matrix: ")
matrix1= np.array([[int(x) for x in input().split()] for i in range (rows)])

print("Enter the entries for the second matrix: ")
matrix2 = np.array([[int(x) for x in input().split()] for i in range(rows)])

result = matrix1 + matrix2
print("Resultant Matrix:")
print(result)

Enter the number of rows: 3
Enter the number of columns: 3
Enter the entries for the first matrix: 
1 2 3
4 5 6
7 8 9
Enter the entries for the second matrix: 
9 8 7
6 5 4
3 2 1
Resultant Matrix:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [3]:
# TASK no. 02. (Matrix Multiplication)

import numpy as np
rows1 = int(input("Enter the number of rows for the first matrix: ")) 
cols1 = int(input("Enter the number of columns for the first matrix: "))

rows2 = int(input("Enter the number of rows for the second matrix: "))
cols2 = int(input("Enter the number of columns for the second matrix: "))

if cols1 != rows2:
    print("Not possible. The number of cols in 1st matrix must be equal to number of rows in 2nd matrix")
else:
    print("Enter the entries for the first matrix: ")
    matrix1 = np.array([[int(x) for x in input().split()] for _ in range(rows1)])
    print("Enter the entries for the second matrix: ")
    matrix2 = np.array([[int(x) for x in input().split()] for _ in range(rows2)])
    
    result = np.dot(matrix1, matrix2)
    print("Resultant Matrix: ")
    print(result)

Enter the number of rows for the first matrix: 1
Enter the number of columns for the first matrix: 2
Enter the number of rows for the second matrix: 2
Enter the number of columns for the second matrix: 2
Enter the entries for the first matrix: 
2 5
Enter the entries for the second matrix: 
1 3
4 6
Resultant Matrix: 
[[22 36]]
